---
# Source: prometheus-blackbox-exporter/templates/podsecuritypolicy.yaml

apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: prometheus-blackbox-exporter-psp
  labels:
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: prometheus-blackbox-exporter
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: prometheus-blackbox-exporter-4.1.0
spec:
  # Prevents running in privileged mode
  privileged: false
  # Required to prevent escalations to root.
  allowPrivilegeEscalation: false
  volumes:
    - configMap
    - secret
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  readOnlyRootFilesystem: true

---
# Source: prometheus-blackbox-exporter/templates/configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-blackbox-exporter
  labels:
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: prometheus-blackbox-exporter
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: prometheus-blackbox-exporter-4.1.0
data:
  blackbox.yaml: |
    modules:
      http_2xx:
        http:
          method: GET
          no_follow_redirects: false
          preferred_ip_protocol: ip4
          tls_config:
            insecure_skip_verify: true
          valid_http_versions:
          - HTTP/1.1
          - HTTP/2
        prober: http
        timeout: 5s
      http_2xx_long:
        http:
          method: GET
          no_follow_redirects: false
          preferred_ip_protocol: ip4
          tls_config:
            insecure_skip_verify: true
          valid_http_versions:
          - HTTP/1.1
          - HTTP/2
        prober: http
        timeout: 1m
      http_post_2xx:
        http:
          body: scope=AU.RETAIL.ACCOUNT.PROFILE.READ
          headers:
            Content-Type: application/x-www-form-urlencoded
          method: POST
          no_follow_redirects: false
          preferred_ip_protocol: ip4
          tls_config:
            insecure_skip_verify: true
          valid_http_versions:
          - HTTP/1.1
          - HTTP/2
        prober: http
        timeout: 5s
      tcp_connect:
        prober: tcp
        timeout: 5s
    

---
# Source: prometheus-blackbox-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-blackbox-exporter
  labels:
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: prometheus-blackbox-exporter
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: prometheus-blackbox-exporter-4.1.0
  annotations:
    {}
    
---
# Source: prometheus-blackbox-exporter/templates/role.yaml

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: prometheus-blackbox-exporter
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: prometheus-blackbox-exporter-4.1.0
  name: prometheus-blackbox-exporter
rules:
  - apiGroups:
    - policy
    resources:
    - podsecuritypolicies
    resourceNames:
    - prometheus-blackbox-exporter-psp
    verbs:
    - use
---
# Source: prometheus-blackbox-exporter/templates/rolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: prometheus-blackbox-exporter
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: prometheus-blackbox-exporter-4.1.0
  name: prometheus-blackbox-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-blackbox-exporter
subjects:
  - kind: ServiceAccount
    name: prometheus-blackbox-exporter
---
# Source: prometheus-blackbox-exporter/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: prometheus-blackbox-exporter
  labels:
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: prometheus-blackbox-exporter
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: prometheus-blackbox-exporter-4.1.0
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9115
      protocol: TCP
  selector:
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: prometheus-blackbox-exporter

---
# Source: prometheus-blackbox-exporter/templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-blackbox-exporter
  labels:
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: prometheus-blackbox-exporter
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: prometheus-blackbox-exporter-4.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-blackbox-exporter
      app.kubernetes.io/instance: prometheus-blackbox-exporter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
    
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-blackbox-exporter
        app.kubernetes.io/instance: prometheus-blackbox-exporter
        app.kubernetes.io/managed-by: Tiller
        helm.sh/chart: prometheus-blackbox-exporter-4.1.0
      annotations:
        checksum/config: b55317df3e181bdf3850124990f531c349aae0b867fa45f6bc0c773322b5f333
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
        
    spec:
      serviceAccountName: prometheus-blackbox-exporter

      restartPolicy: Always
      containers:
        - name: blackbox-exporter
          image: "asia.gcr.io/anz-cx-ob-build-np-de5569/prom/blackbox-exporter:v0.16.0"
          imagePullPolicy: IfNotPresent
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          args:
            - "--config.file=/config/blackbox.yaml"
          resources:
            {}
            
          ports:
            - containerPort: 9115
              name: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - name: config
          configMap:
            name: prometheus-blackbox-exporter

---
# Source: prometheus-blackbox-exporter/templates/daemonset.yaml


---
# Source: prometheus-blackbox-exporter/templates/ingress.yaml

---
# Source: prometheus-blackbox-exporter/templates/poddisruptionbudget.yaml


---
# Source: prometheus-blackbox-exporter/templates/prometheusrule.yaml


---
# Source: prometheus-blackbox-exporter/templates/servicemonitor.yaml



